version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8 # Specify the runtime if needed (or omit if not necessary)
    commands:
      - echo Installing necessary packages...
      - apt-get install -y zip # Install zip utility if not already

  pre_build:
    commands:
      - echo Pre-build stage...
      - echo Checking if S3 bucket is accessible
      - aws s3 ls s3://custom-control-tower-configuration-593793039129-us-west-2

  build:
    commands:
      - echo Starting build process...
      - echo Creating zip file from the repository folder
      - zip -r custom-control-tower-configuration.zip custom-control-tower-configuration/ # Replace 'folder-to-zip' with your folder's name

  post_build:
    commands:
      - echo Build completed. Uploading to S3...
      - aws s3 cp custom-control-tower-configuration.zip s3://custom-control-tower-configuration-593793039129-us-west-2/ # Replace with your S3 bucket name and path

artifacts:
  files:
    - custom-control-tower-configuration.zip
  discard-paths: yes
